eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
#    metadata-map:
#      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
#    prefer-same-zone-eureka: false
spring:
  cloud:
    #    kubernetes:
    #      enabled: false
    discovery:
      enabled: true
#    client:
#      hostname: ${eureka.instance.hostname}
