#for local load balance demo, override application.yml config
server:
  port: 8081

eureka:
  client:
    enabled: false

instance:
  name: ${spring.application.name}-one

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
spring:
  jackson:
    date-format: "yyyy-MM-dd't'HH:mm:ss.SSSZ"