server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
#    metadata-map:
#      zone: zone2
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    refresh:
      enable: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
#    prefer-same-zone-eureka: true
spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: true
    client:
      hostname: ${eureka.instance.hostname}

instance:
  name: ${spring.application.name}-${random.value}
