server:
  port: 8081

spring:
  application:
    name: greeting-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test
  main:
    lazy-initialization: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: greeting-server
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: java.lang.String
            trusted:
              packages: com.arch.greeting
      auto-offset-reset: latest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            add:
#              type:
#                headers: false
